name: fastfood
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.1.0
  scoped_model: ^1.0.1
  carousel_pro: ^1.0.0
  flutter_masked_text: ^0.8.0
  font_awesome_flutter: ^8.8.1
  flutter_ticket_widget: ^0.0.1
  flare_flutter: ^2.0.1
  date_format: ^1.0.8
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/img/
    - assets/icons/
    - assets/animation/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FontBlack
      fonts:
        - asset: assets/font/SFUIDisplay-Black.otf

    - family: FontBold
      fonts:
        - asset: assets/font/SFUIDisplay-Bold.ttf

    - family: FontHeavy
      fonts:
        - asset: assets/font/SFUIDisplay-Heavy.otf

    - family: FontLight
      fonts:
        - asset: assets/font/SFUIDisplay-Light.ttf

    - family: FontMedium
      fonts:
        - asset: assets/font/SFUIDisplay-Medium.otf

    - family: FontRegular
      fonts:
        - asset: assets/font/SFUIDisplay-Regular.otf

    - family: FontSemiBold
      fonts:
        - asset: assets/font/SFUIDisplay-SemiBold.otf

    - family: FontThin
      fonts:
        - asset: assets/font/SFUIDisplay-Thin.otf

    - family: FontUltralight
      fonts:
        - asset: assets/font/SFUIDisplay-Ultralight.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
